export const CHANGE_DATA = 'CHANGE_DATA';
export const CHANGE_PTS_VARIABLES = 'CHANGE_PTS_VARIABLES';
export const CHANGE_SIGNATURE_VARIABLES = 'CHANGE_SIGNATURE_VARIABLES';
export const CHANGE_UBER_VARIABLES = 'CHANGE_UBER_VARIABLES';